### ISSUE TITLE
Ph Tool in homebridge-lip is missing

### ISSUE THREAD

**Issue by Nastras** [ebaauw/ph.sh#1]
Good morning,

as announced I am in the process of reinstalling my server. Since I no longer need your Hue plugin in the future because I'm switching to your deconz plugin I saw that you have created a new way to access the API. Since I currently have not yet dealt with it in more detail I wanted to continue to use your PH tool. In the future I will change it. 

For this I have installed the Homebridge-lib package as described on this homepage. Unfortunately I found out that the PH tool is not included?

I have now installed the homebridge-hue plugin to access the PH tool. Is there a way to install only the PH tool without homebridge-hue?

Regards
Nastra

**Comment by ebaauw** [comment]
`ph` is not part of homebridg-lib; it's part of Homebridge Hue.  Homebridge deCONZ contains the `deconz` tools, which basically does the same for the deCONZ gateway that `ph` does for the Hue bridge and/or deCONZ gateway.

Instead of installing homebridge-lib, you should install `hb-lib-tools` for the commands-line tools `hap`, `json`, `sysinfo` and `upnp`, see https://github.com/ebaauw/homebridge-lib#installation.

I plan on splitting off the non-Homebridge stuff from Homebridge deCONZ, incl. `deconz` into `hb-deconz-tools`, once I'll have refactored the code to provide a cleaner cut.  I plan on splitting off `ph` from Homebridge Hue eventually as well, after removing the deCONZ support from Homebridge Hue.  That's going to be a while.

**Comment by Nastras** [comment]
I had understood this sentence to mean that it is included in the homebridge-lib package. 

![9ABA1CE5-7D59-44BF-9AE1-B05398B07796](https://user-images.githubusercontent.com/27686185/227114459-f5436243-400f-4db0-9284-fc2e2dc3fd20.jpeg)


But good to know what your plan is. I will continue to use the ph tool for smaller things for now and then look at the deconz tool more closely in the future. Would have been nice if I no longer had to install the homebridge-hue plugin. But also not really bad.

Ps. I haven't added any devices to Homekit yet because I have to prepare two more Raspberry Pi with deconz and wait for iOS 16.4 release. I decided to split my network into three deconz networks. I think I'm on the safe side as far as network stability is concerned. 

I am curious how your new plugin incl. the group function performs. I will get back to you on this 😉

Thanks a lot!
